services:
  - type: web
    name: ai-carbon-system-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
    plan: free
    region: singapore
